project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Lu Zhao"
  date: "2023/2/11"
  navbar: 
    collapse: true
    collapse-below: lg
    background: light
    search: true
    right: 
      - icon: github
    repo-url: https://github.com/luzhao2000/CASA0023Learning_Diary.git
  chapters:
    - index.qmd
    - intro.qmd
    - Week1.qmd
    - Week2.qmd
    - Week3.qmd
    - Week4.qmd
    - Week5.qmd
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo,flatly]
      dark: [cosmo,darkly]
  pdf:
    documentclass: scrreprt

editor: visual

