# Introduction {.unnumbered}

## Background

Hello everyone, my name is Lu, and I am a CASA Masters student enrolled in September 2022 and will graduate in September 2023. My course is Urban Spatial Science, which is an interdisciplinary specialisation in GIS, remote sensing, quantitative analysis, data science, agent-based modelling, and theories related to smart cities.

I chose this course because I am very interested in satellites and remote sensing images. I can see through these images the long stretches of mountains and the endless sea, which are the places that I might not otherwise go. I think the technology of remote sensing provides me with another way to understand and explore our planet.

## Education experience

I attended Capital Normal University and the University of Waterloo for my undergraduate studies from 2018 to 2022. At Capital Normal University, I studied Remote Sensing Science and Technology, and in my courses, I was mainly involved in GIS, remote sensing, advanced mathematics, algebra, probability and statistics, and programming.

I am very fortunate to be able to participate in the 2+2 externship program between Capital Normal University and the University of Waterloo in Canada. During my two years of study at the University of Waterloo, I majored in Geomatics with a focus on the application of GIS and remote sensing technology and the completion of projects, and I also minored in Mathematics.

I am currently studying Urban Spatial Science at UCL.

## Professional experience

I have a relatively extensive professional experience.

Firstly, during my undergraduate studies I was involved in 3S Field Investigation at Beijing Wild Duck Lake Wetland Nature Reserve, where I used spectral feature curve data and high-resolution remote sensing imagery from field surveys to perform supervised and unsupervised classification based on ENVI and object-oriented classification based on eCognit. The analysis of land use change was carried out using supervised classification based on ENVI, unsupervised classification and object-oriented classification based on eCognition.

In addition, I have worked on ArcGIS Pro and ENVI to analyzing the urban area ahanges from 1975 to 2010 in Toronto and Montreal, analyzing the factors that influence the unemployment rate in London from 2012 to 2021 based on Python, and geospatial weighted regression analysis and multi-factor regression analysis to analyse the factors influencing the spread of COVID-19 in Hubei Province, China by using ArcGIS.

## Interests

I have a relatively strong interest in smart cities and urban analytics. In my previous internship work I have learned about some examples of projects where smart cities were actually used, which made me very interested in digital, more scientifically planned and managed urban systems. At the same time, through the combination of large amounts of data computing and aspects such as GIS, cities can be managed more intelligently and efficiently.

In my spare time, I really enjoy reading books and travelling. I think reading allows me to understand and learn new knowledge and cultures more quickly, and to stay creative and imaginative. Travelling allows me to measure the world and open my eyes through my own feet, and is also a way to release stress. I also enjoy yoga and cycling, as proper exercise not only keeps me fit and healthy so that I can focus more when studying, but also relieves tension and heavy coursework.

## Expectations

Based on my ideas and my basic situation, I hope that through this course I will become more familiar with the knowledge related to remote sensing and be able to consolidate the theoretical knowledge with practical applications. In addition, I also would like to learn more about cutting-edge technologies and developments in this field as a way to expand my knowledge.
